### ISSUE TITLE
Missing class in Mars Java2HTMLEntityReader

### ISSUE THREAD

**Issue by branflake2267** [gwt-plugins/gwt-eclipse-plugin#70]
------
STATUS
------
pluginId            org.eclipse.jface
pluginVersion       3.11.0.v20150426-1512
code                2
severity            4
message             Problems occurred when invoking code from plug-in: "org.eclipse.jface".
fingerprint         2dec67f9

Exception:java.lang.NoClassDefFoundError: org/eclipse/jdt/internal/formatter/comment/Java2HTMLEntityReader
	 at com.google.gwt.eclipse.oophm.views.hierarchical.LogContent.convertToHtmlContent(LogContent.java:237)
	 at com.google.gwt.eclipse.oophm.views.hierarchical.LogContent.buildLabelHtml(LogContent.java:332)
	 at com.google.gwt.eclipse.oophm.views.hierarchical.LogContent.updateDetailsPane(LogContent.java:599)
	 at com.google.gwt.eclipse.oophm.views.hierarchical.LogContent.access$4(LogContent.java:568)
	 at com.google.gwt.eclipse.oophm.views.hierarchical.LogContent$4.selectionChanged(LogContent.java:454)
	 at org.eclipse.jface.viewers.Viewer$2.run(Viewer.java:163)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	 at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	 at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:160)
	 at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2197)
	 at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1228)
	 at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1257)
	 at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:242)
	 at org.eclipse.jface.util.OpenStrategy.access$4(OpenStrategy.java:236)
	 at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:408)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1481)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1504)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1489)
	 at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1293)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	 at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	 at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	 at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	 at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	 at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	 at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:483)
	 at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	 at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	 at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

------
REPORT
------
anonymousId         7689a93d-d258-431c-b536-d31ae368c2c5
name                Brandon Donnelson
email               branflake2267@gmail.com
comment             
eclipseBuildId      4.5.0.I20150430-1445
eclipseProduct      org.eclipse.epp.package.jee.product
javaRuntimeVersion  1.8.0-ea-b123
osgiWs              cocoa
osgiOs              MacOSX
osgiOsVersion       10.10.3
osgiArch            x86_64
logMessage          false
ignoreSimilar       false

-------
BUNDLES
-------
name                com.google.gwt.eclipse.oophm
version             0.0.0.201505180557

name                org.eclipse.core.databinding.observable
version             1.5.0.v20150422-0725

name                org.eclipse.core.databinding
version             1.5.0.v20150422-0725

name                org.eclipse.core.runtime
version             3.11.0.v20150405-1723

name                org.eclipse.e4.ui.workbench
version             1.3.0.v20150429-1329

name                org.eclipse.e4.ui.workbench.swt
version             0.13.0.v20150422-0725

name                org.eclipse.equinox.app
version             1.3.300.v20150423-1356

name                org.eclipse.equinox.launcher
version             1.3.100.v20150423-1351

name                org.eclipse.jface
version             3.11.0.v20150426-1512

name                org.eclipse.swt
version             3.104.0.v20150430-1253

name                org.eclipse.ui
version             3.107.0.v20150423-1329

name                org.eclipse.ui.ide.application
version             1.1.0.v20150422-0725

name                org.eclipse.ui.ide
version             3.11.0.v20150429-0914

**Comment by branflake2267** [comment]
Update in the works for Java2HTMLEntityReader. Import changes and works for both kepler and luna.

**Comment by ttt43ttt** [comment]
I have this issue too. @branflake2267 How can I "import changes"?

**Comment by branflake2267** [comment]
The import for Java2HTMLEntityReader is in the Eclipse GWT plugin and has to be changed in the build.

**Comment by branflake2267** [comment]
#83 is merged, building snapshot tonight and will test the nightly tomorrow

**Comment by yuktgsl** [comment]
Issue appears fixed now. Thanks

**Comment by luizmineo** [comment]
Is there an updated build available?

**Comment by branflake2267** [comment]
Thanks for the info @yuktgsl. I've tested it too and works. I'll start the production deployment build.

**Comment by branflake2267** [comment]
http://130.211.135.234/viewType.html?buildTypeId=GwtPlugin_GwtPluginDeploy - it's running and will push out a new artifacts to the repo shortly. .

**Comment by gzattara** [comment]
There will be an update (through eclipse) available soon?

**Comment by branflake2267** [comment]
If all went ok, goto the help check for updates, if that won't work goto install new software and it should show an update.

**Comment by dyb22700** [comment]
Hi branflake2267,

I have installed Mars Release (4.5.0) Build id: 20150621-1200 + GWT Plugin v 3.8.0 r44 and still have this Java2HTMLEntityReader popup dialog error constantly showing up, when this fix will be available or if you have milestone or drop link as the check for update on MARS does not bring anything to update.

Thanks

**Comment by branflake2267** [comment]
You have an older build I think. I have 20150729. This should be in the main repo and the snapshot repo. Can you check by going to install updates, and see if it pops up in the list. Or goto install new software and see if it has the option with the update?

![screen shot 2015-08-19 at 9 57 35 am](https://cloud.githubusercontent.com/assets/1326504/9363026/bc95a988-4658-11e5-9a95-500ccc2917e6.png)

**Comment by dyb22700** [comment]
Here my version and no update is found, weird ?

![gwt plugin 4 4 java2htmleditor](https://cloud.githubusercontent.com/assets/1922234/9377940/907a7912-471d-11e5-81b1-b5a886a03197.png)

**Comment by dyb22700** [comment]
My update site : GWT - https://dl.google.com/eclipse/plugin/4.4 and apparently all bundle version are stamped 2014, not 2015...

**Comment by dyb22700** [comment]
branflake2267, 
Thank you for your reply,
I found on your snapshot that the version x.y.z is 0.0.0 instead of 3.8.0 ? Are you using a different updatesite on GWT Plugin ? Any idea how to disable or fix this issue ?
Thanks.

**Comment by branflake2267** [comment]
I'm not sure what is going on yet. But there is an option to try the snapshot update site: http://storage.googleapis.com/gwt-eclipse-plugin/snapshot - I compiled all the fixes to this site first. There is always that possibility I am using the wrong update site, I get mixed up at times, but I try to download a clean copy and try it out. That might be an option just to verify, download a new copy, be sure to name the working directory something different too so it doesn't interfere with your current working directory. Then try the production update site. On a side note, I'm under the gun for a release at the and once I come up for air in the next couple weeks I plan on fixing some bugs before several winter conferences that are coming up. This means I'm slightly limited on time I can help at the moment, but I'd like to make sure you can get around the issue.

**Comment by branflake2267** [comment]
There could be a slim chance I got my repos crossed, and didn't update the production one, but I thought I had. If someone can double check that, would be handy. :)

**Comment by Addow** [comment]
branflake2267, I can hereby confirm that I had the exact same situation as dyb22700. Updating through Eclipse (Mars) via https://dl.google.com/eclipse/plugin/4.4 did not work, updating via the snapshot link you provided above was a success: v0.0.0.201507191805.

GWT development running fine again and no missing class exceptions! Thanks.

**Comment by branflake2267** [comment]
Thanks for the update. From the sounds of it the artifacts didn't get copied into the production repo. I'm slammed at the moment will fix this soon.

**Comment by dyb22700** [comment]
Thank you for the update on this temporary workaround, keep in touch branflake2267.

Envoyé de mon iPhone

**Comment by ias-dt** [comment]
Is there an ETA for this fix to become available via prod repo?

**Comment by branflake2267** [comment]
Sorry for the delay. I've got a release at work that is taking all my
effort at the moment. Once things settle which should be in the next couple
weeks. I'm hoping to get this done in august with some other fixes.

Thanks,
Brandon

Have a good day,
Brandon Donnelson
+Follow Me <https://plus.google.com/u/0/111739836936169749229/posts>

**Comment by NightFox7** [comment]
Is this bug now fixed in the current release? Because I still have the mentioned problem.

**Comment by branflake2267** [comment]
It has, but I have neglected to update the production in fear of something going wrong yet. So you'll have to use the snapshot repo to get it. I have to rebuild and deploy yet yet. Sorry I'm under the gun for a release at the moment, but after I plan on doing a round of bug fixes. I'm getting closer.

**Comment by davepuchyr** [comment]
Thanks for all your effort on this!  (I fully understand and appreciate your constraints.) 

Sincerely,

Dave

**Comment by branflake2267** [comment]
Shoot I know why this didn't show up in the production deploy, I needed to renew the oauth token for uploading. I've got some more fixes to test in the snapshot and will upload soon.

**Comment by geoffreywiseman** [comment]
Would be nice for this to go into the production site -- I'm updating a friend's eclipse right now to the snapshot version to make this Java2HTMLEntityReader error go away.

**Comment by branflake2267** [comment]
I've been thinking the same thing today. :)

**Comment by branflake2267** [comment]
By the way, I'm waiting on build agent for Eclipse to be setup at work, which I'm hoping smooths the build process out more.

**Comment by Cracky5457** [comment]
This issue is "fixed" ? 

Can we clearly know hot to fix that issue ?

**Comment by branflake2267** [comment]
It's fixed in the snapshots repo. I'll aim to get the production updated by hand shortly. I've been hoping something else comes through but it's happening slower than I thought.

**Comment by branflake2267** [comment]
I'm pushing a new build to the release repo, it should be done shortly.

**Comment by branflake2267** [comment]
The artifacts have been pushed up to the production repo.

**Comment by dishycrayon** [comment]
I set up a new laptop with eclipse to Mars today and am now getting this error. I updated to 4.4 as it says in this thread but it did not resolve the issue. I also not able to access the snapshot link you had above, is this something that will get resolved soon or should I downgrade?  Thanks

**Comment by geoffreywiseman** [comment]
Were you using the release repo here?
http://storage.googleapis.com/gwt-eclipse-plugin/release

(I haven't upgraded to Eclipse 4.5 for GWT development myself, just trying to help.)

**Comment by branflake2267** [comment]
Be sure to remove the former GPE plugin and install the GWT Plugin fork from the link in the previous comment. That should fix it.

**Comment by zip184** [comment]
Thanks for fix!  I got it using http://storage.googleapis.com/gwt-eclipse-plugin/snapshot site.  Do you know when this will be pushed to the https://dl.google.com/eclipse/plugin/4.4 site?

**Comment by branflake2267** [comment]
I don't know what Google's plans are with their plugin. I've forked it to help move things along.

**Comment by chiang9** [comment]
Do we also need to reinstall the App Engine SDK, Google App Engine Maven Integration, GWT SDK? Or we only need to re-install the Google Plugin for Eclipse 4.4 and remove the GPE plugin?

**Comment by robbityrob** [comment]
Brandon - is there any way to download the latest snapshot as a zip to install it within eclipse manually?  We have some developers here that are offsite and are having network issues connecting to the snapshot update URL.  I see on the GitHub Readme you have a link for the cloud browser for builds but I don't have privs to see anything when I click on the link and login.  Is there some place else I can grab it as a zip for my devs?

Thanks so much!

**Comment by JonasDann** [comment]
It is not working for me when I only install the Google Plugin from the snapshot site. Is the Plugin from the snapshot site installing m2e with the Google Plugin?

**Comment by branflake2267** [comment]
I've deployed the fix on both the release site and snapshot site. I'm not sure what's going on. I suspect a clean install might be needed or something else is going on that I'm not aware of and I'll need more info on configuration.

**Comment by oliverdrummond** [comment]
Still having the same problem.

When I try to use http://storage.googleapis.com/gwt-eclipse-plugin/snapshot I get the "error":
> Cannot complete the request.  See the error log for details.
"Google Plugin for Eclipse 4.4" will be ignored because a newer version is already installed. 

And when I try to use https://dl.google.com/eclipse/plugin/4.4, it says: 
> All items are installed

Any ideia of what might be happening?

**Comment by branflake2267** [comment]
I suspect the old plugin is installed. I'd suggest downloading Eclipse EE for Mars and installing it again. If that works, go back to the old install and uninstall all the plugin parts and try again.

**Comment by cellepo** [comment]
This solution worked for me, thanks!

**Comment by Darker** [comment]
I am using the google STS plug-in (installed right now) and it also has this error. Is it possible to fix this by simply replacing the `.class` file that causes the problems?

**Comment by branflake2267** [comment]
I'm not sure. A fix is coming out in the mainline down the road.

**Comment by Darker** [comment]
The bug is 5 months old. Is there any way I could get the fixed version, for example from this repository? The problem makes my work much harder :(

I tried to look for updates but everything is already up-to-date in my IDE...

**Comment by branflake2267** [comment]
It is fixed in this repo. If you're not seeing it, you don't have the latest download.

**Comment by branflake2267** [comment]
I'd suggest; try a clean install and verify.
